services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_local_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  prisma-init:
    build:
      context: .
    env_file:
      - .env.local
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/my_local_db
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        echo '🌱 Initializing Prisma (generate, push, seed)...' &&
        npm run db:generate &&
        npm run db:push &&
        npm run db:seed &&
        echo '✅ Prisma setup complete.'
      "
    volumes:
      - .:/app
      - /app/node_modules

  app:
    build:
      context: .
    env_file:
      - .env.local
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/my_local_db
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      prisma-init:
        condition: service_completed_successfully
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
